# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce57368bae4a583b015268e4c78e3e8a2dd97838728bb3e26897ac0f68edefb249b6b18487c6fbbcfcf987f5c945b13cf9589a0ed9be981773491457a7f3bba5

test:
  secret_key_base: 0775e682bd9c8b39e3c50481234e6b326b893007a16d836065a97edd872b57a4ca4d49b8eba724309f30f6ab335f5dd56bea7951ea0eceacadbaefebba991aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
